service: knowledgebowl
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 1024
  stage: ${opt:stage, 'dev'}
  environment: 
    ENVIRONMENT: ${self:custom.secrets.ENVIRONMENT}
    BASE_URL: ${self:custom.secrets.BASE_URL}
    DB_CLIENT: ${self:custom.secrets.DB_CLIENT}
    DB_CONNECTION: ${self:custom.secrets.DB_CONNECTION}
    MAILGUN_API_KEY: ${self:custom.secrets.MAILGUN_API_KEY}
    MAILGUN_DOMAIN: ${self:custom.secrets.MAILGUN_DOMAIN}
    MAILGUN_OVERRIDE_EMAIL: ${self:custom.secrets.MAILGUN_OVERRIDE_EMAIL}
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    SALT_ROUNDS: ${self:custom.secrets.SALT_ROUNDS}
    API_REGION: !Ref AWS::Region
plugins:
  - serverless-secrets-plugin
  - serverless-offline
custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}
functions:
  app:
    handler: app.handler
    role: lambdaExecutionRole
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
resources:
  Resources:
    lambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /roles/default/
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service}-${opt:stage, self:provider.stage}-lambdaDefaultPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    Fn::Join:
                      - ":"
                      - - "arn:aws:logs"
                        - Ref: "AWS::Region"
                        - Ref: "AWS::AccountId"
                        - "log-group:/aws/lambda/*:*:*"
                - Effect: Allow
                  Action:
                    - ses:SendEmail
                  Resource:
                    Fn::Join:
                      - ":"
                      - - "arn:aws:ses"
                        - Ref: "AWS::Region"
                        - Ref: "AWS::AccountId"
                        - "identity/*"